"""Generate embedded antialiased Manrope glyphs. Requires Pillow 11.3.0.

Run from the repository root. Font is distributed under firmware/fonts/OFL.txt.
The committed header means firmware builds need neither Python nor an SD card.
"""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
SIZES = [(11, 550), (16, 600), (24, 650), (36, 650), (48, 650)]


def build():
    output = ['// Generated by tools/generate_fonts.py; Manrope, SIL OFL 1.1.',
              '#pragma once', '#include <Arduino.h>',
              'struct SmoothGlyph { uint32_t offset; uint8_t w,h,advance; int8_t x,y; };',
              'struct SmoothFont { const uint8_t *pixels; const SmoothGlyph *glyphs; };']
    for index, (size, weight) in enumerate(SIZES):
        font = ImageFont.truetype(str(ROOT/'firmware/fonts/Manrope.ttf'), size)
        font.set_variation_by_axes([weight])
        cap_top = font.getbbox('M', anchor='ls')[1]
        pixels, glyphs = [], []
        for code in range(32, 127):
            char = chr(code)
            left, top, right, bottom = font.getbbox(char, anchor='ls')
            w, h = right-left, bottom-top
            image = Image.new('L', (max(1, w), max(1, h)))
            ImageDraw.Draw(image).text((-left, -top), char, font=font, fill=255, anchor='ls')
            alpha = [round(v/17) for v in image.getdata()] if w*h else []
            glyphs.append((len(pixels), w, h, round(font.getlength(char)), left, top-cap_top))
            if len(alpha) % 2:
                alpha.append(0)
            pixels.extend((alpha[i]<<4)|alpha[i+1] for i in range(0, len(alpha), 2))
        output.append(f'const uint8_t fontPixels{index}[] PROGMEM = {{')
        output.extend(','.join(map(str,pixels[i:i+32]))+',' for i in range(0,len(pixels),32))
        output.append('};')
        output.append(f'const SmoothGlyph fontGlyphs{index}[] PROGMEM = {{')
        output.extend('{'+','.join(map(str,g))+'},' for g in glyphs)
        output.append('};')
    output.append('const SmoothFont smoothFonts[] = {')
    output.extend(f'{{fontPixels{i},fontGlyphs{i}}},' for i in range(len(SIZES)))
    output.append('};')
    (ROOT/'firmware/CodexDesk/smooth_fonts.h').write_text('\n'.join(output)+'\n', encoding='utf-8')


if __name__ == '__main__':
    build()
